---
name: Test Action

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test Action
    env:
      SCW_REGION: fr-par
      SCW_FUNCTION_NAME: hello-world
      SCW_NAMESPACE_ID: edb6f264-dbfc-4346-8201-12f9d3a9ce5b
      SCW_RUNTIME: python311
    steps:
      - uses: moreaupascal56/scaleway-serverless-deploy-action@main
        with:
          function_root: tests/src
          requirements_txt_path: tests/requirements.txt

          scw_function_name: ${{ env.SCW_FUNCTION_NAME }}
          scw_namespace_id: ${{ env.SCW_NAMESPACE_ID }}
          scw_region: ${{ env.SCW_REGION }}
          scw_runtime: ${{ env.SCW_RUNTIME }}
